### ISSUE TITLE
Broken cv2 module for python3.6

### ISSUE THREAD

**Issue by carterbox** [conda-forge/opencv-feedstock#258]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Latest build of py-opencv for `python=3.6` fails to import the `cv2` module.
```
(opencv) dching@RADIO:~/Documents/tike$ conda list py-opencv
# packages in environment at /home/dching/miniconda3/envs/opencv:
#
# Name                    Version                   Build  Channel
py-opencv                 4.5.0            py36he448a4c_5    conda-forge
(opencv) dching@RADIO:~/Documents/tike$ python -c "import cv2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
(opencv) dching@RADIO:~/Documents/tike$ 
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/dching/miniconda3/envs/opencv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h7979940_1007    conda-forge
certifi                   2020.12.5        py36h5fab9bb_0    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
ffmpeg                    4.3.1                hca11adc_2    conda-forge
fontconfig                2.13.1            h736d332_1003    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.66.4               hcd2ae1e_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.2               h3560a44_1    conda-forge
harfbuzz                  2.7.4                h5cf4720_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1113    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                6_openblas    conda-forge
libcblas                  3.9.0                6_openblas    conda-forge
libclang                  11.0.0          default_ha5c780c_2    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libglib                   2.66.4               h164308a_1    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                6_openblas    conda-forge
liblapacke                3.9.0                6_openblas    conda-forge
libllvm11                 11.0.0               he513fc3_0    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libopencv                 4.5.0                    py36_5    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mysql-common              8.0.22               ha770c72_1    conda-forge
mysql-libs                8.0.22               h1fd7589_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.60                 hb5efdd6_0    conda-forge
numpy                     1.19.4           py36h2aa4a07_2    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py-opencv                 4.5.0            py36he448a4c_5    conda-forge
python                    3.6.12          hffdb5ce_0_cpython    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
qt                        5.12.9               h9d6b050_2    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py36h9880bd3_2    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
x264                      1!161.3030           h7f98852_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : opencv
    active env location : /home/dching/miniconda3/envs/opencv
            shell level : 4
       user config file : /home/dching/.condarc
 populated config files : /home/dching/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.1=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dching/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dching/miniconda3/pkgs
                          /home/dching/.conda/pkgs
       envs directories : /home/dching/miniconda3/envs
                          /home/dching/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Linux/5.4.0-59-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

**Comment by carterbox** [comment]
Here's the index.json:
```json
{
  "arch": "x86_64",
  "build": "py36he448a4c_5",
  "build_number": 5,
  "depends": [
    "libopencv 4.5.0 py36_5",
    "numpy >=1.16.6,<2.0a0",
    "python >=3.6,<3.7.0a0",
    "python_abi 3.6.* *_cp36m"
  ],
  "license": "BSD-3-Clause",
  "license_family": "BSD",
  "name": "py-opencv",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1609679199797,
  "version": "4.5.0"
}
```
and the paths.json:
```json
{
  "paths": [],
  "paths_version": 1
}
```

Looks like nothing is being installed. Is py-opencv supposed to be a meta-package?

**Comment by hmaarrfk** [comment]
i think this is supposed to work.

Mostly, the reorganization was supposed to help downstream packages pin correctly

https://github.com/conda-forge/opencv-feedstock/blob/master/recipe/meta.yaml#L2


Because of complications in building opencv, `py-opencv` simply installs `libopencv` which includes all the files.

We can probably add a hash to the libopencv build, but that doesn't seem to be the problem.

Can you give the output of `where python`

**Comment by hmaarrfk** [comment]
```
conda create --name opencv py-opencv python=3.6
conda activate opencv
python -c "import cv2"
```

I can confirm that the package works for python 3.7, but not 3.6 on linux.

**Comment by carterbox** [comment]
```bash
$ which python
/home/dching/miniconda3/envs/opencv/bin/python
```

My `(opencv)` environment was built by requesting `python=3.6` and `py-opencv`

**Comment by hmaarrfk** [comment]
```
16:35 $ mamba install python=3.6

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.6) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.6']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
Transaction

  Prefix: /home/mark/miniconda3/envs/opencv

  Updating specs:

   - python==3.6


  Package       Version  Build               Channel                    Size
──────────────────────────────────────────────────────────────────────────────
  Change:
──────────────────────────────────────────────────────────────────────────────

  certifi     2020.12.5  py37h89c1867_0      installed                      
  certifi     2020.12.5  py36h5fab9bb_0      conda-forge/linux-64     Cached
  libopencv       4.5.0  py37_5              installed                      
  libopencv       4.5.0  py36_5              conda-forge/linux-64     Cached
  numpy          1.19.4  py37haa41c4c_2      installed                      
  numpy          1.19.4  py36h2aa4a07_2      conda-forge/linux-64     Cached
  py-opencv       4.5.0  py37h888b3d9_5      installed                      
  py-opencv       4.5.0  py36he448a4c_5      conda-forge/linux-64     Cached
  setuptools     49.6.0  py37he5f6b98_2      installed                      
  setuptools     49.6.0  py36h9880bd3_2      conda-forge/linux-64     Cached

  Downgrade:
──────────────────────────────────────────────────────────────────────────────

  python          3.7.9  hffdb5ce_0_cpython  installed                      
  python         3.6.12  hffdb5ce_0_cpython  conda-forge/linux-64     Cached
  python_abi        3.7  1_cp37m             installed                      
  python_abi        3.6  1_cp36m             conda-forge/linux-64     Cached

  Summary:

  Change: 5 packages
  Downgrade: 2 packages

  Total download: 0  B

──────────────────────────────────────────────────────────────────────────────

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(opencv) ✔ ~ 
16:35 $ python -c "import cv2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
```

**Comment by hmaarrfk** [comment]
Unfortunately, i don't know the syntax to disable a particular build.....

**Comment by hmaarrfk** [comment]
seems like build 6 is open too.

The recicpe was designed before pypy, and as such there is a conflict between the two pypy and non pypy builds.

**Comment by sambbhavgarg** [comment]
did the trick for me on windows 10, Python 3.6.12 - 
`conda remove py-opencv libopencv opencv
conda install py-opencv`

I think i installed libopencv separately earlier and just simply installing py-opencv is enough.

**Comment by hmaarrfk** [comment]
Glad we got it working for you.
