### ISSUE TITLE
autotick bot has a problem

### ISSUE THREAD

**Issue by wolfv** [conda-forge/opencv-feedstock#280]
This is from the autotick bot logs:

```
We found a problem parsing the recipe for version '4.5.3': 

ParserError('while parsing a block mapping',   in "", line 111, column 5:
        requires:
        ^ (line: 111), "expected , but found ''",   in "", line 183, column 9:
            - export CONDA_BUILD_SYSROOT=<{  ... 
            ^ (line: 183))

traceback:
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/migrators/version.py", line 506, in migrate
    cmeta = CondaMetaYAML(fp.read())
  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/recipe_parser/_parser.py", line 455, in __init__
    self.meta = self._parser.load("".join(lines))
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 120, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 216, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
  File "/usr/share/miniconda/envs/run_env/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 611, in parse_block_mapping_key
    raise ParserError(
```

**Comment by hmaarrfk** [comment]
This is still a problem:
```
bot error (
[bot CI job](https://github.com/regro/cf-scripts/actions/runs/10975355826)
): main:
Error running 'conda-forge-feedstock-ops-container rerender --log-level info --timeout 900' in container - error RuntimeError raised:
'Failed to rerender.
output: Adding in variants from internal_defaults
Adding in variants from /tmp/tmp2b1lbjqd/conda-smithy/conda_build_config.yaml
Adding in variants from /tmp/tmpo0e91u3a/opencv-feedstock/recipe/conda_build_config.yaml
Adding in variants from argument_variants
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.09.21.17.22.43
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmp2b1lbjqd/conda-smithy
INFO:conda_smithy.configure_feedstock:README rendering is skipped
INFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped
INFO:conda_smithy.configure_feedstock:openvino202430.yaml is closed now. Removing
INFO:conda_smithy.configure_feedstock:python312.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:pypy38.yaml is closed now. Removing
INFO:conda_smithy.configure_feedstock:ffmpeg7.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:numpy2.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:openvino202440.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:harfbuzz9.yaml is closed now. Removing
WARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/python312.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/numpy2.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/ffmpeg7.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/openvino202440.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/python312.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/numpy2.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/ffmpeg7.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/openvino202440.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/python312.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/numpy2.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/ffmpeg7.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/openvino202440.yaml
INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/python312.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/numpy2.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/ffmpeg7.yaml,/tmp/tmp2b1lbjqd/conda-smithy/share/conda-forge/migrations/openvino202440.yaml
Traceback (most recent call last):
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py", line 2010, in _get_contents
    rendered = template.render(environment=env)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/tmp/tmpo0e91u3a/opencv-feedstock/recipe/meta.yaml", line 185, in top-level template code
    {{ opencv_libs.append("shape") or "" }}
^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'CONDA_BUILD_SYSROOT' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/cf-scripts/bin/conda-smithy", line 10, in 
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", line 758, in main
    args.subcommand_func(args)
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", line 601, in __call__
    self._call(args, args.temporary_directory)
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py", line 604, in _call
    configure_feedstock.main(
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2782, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 1868, in render_azure
    return _render_ci_provider(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 1090, in _render_ci_provider
    metas = _conda_build_api_render_for_smithy(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 890, in _conda_build_api_render_for_smithy
    metadata_tuples = render_recipe(
                      ^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/render.py", line 994, in render_recipe
    return distribute_variants(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/render.py", line 883, in distribute_variants
    mv.parse_until_resolved(
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py", line 1364, in parse_until_resolved
    self.parse_again(
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py", line 1273, in parse_again
    self._get_contents(
  File "/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py", line 2020, in _get_contents
    raise CondaBuildUserError(
conda_build.exceptions.CondaBuildUserError: Failed to render jinja template in /tmp/tmpo0e91u3a/opencv-feedstock/recipe/meta.yaml:
'CONDA_BUILD_SYSROOT' is undefined
```

**Comment by hmaarrfk** [comment]
I don't think it is fixed quite yet.

**Comment by hmaarrfk** [comment]
Hmm i think i maybe finally got it.

Lets wait to see:
https://conda-forge.org/status/migration/?name=openvino202440

**Comment by hmaarrfk** [comment]
success
https://github.com/conda-forge/opencv-feedstock/pull/431
